### ISSUE TITLE
请问下flyingthings数据集下载后解压缩是大概有1.5T左右的大小吗？

### ISSUE THREAD

**Issue by yeyeliangshen** [IRMVLab/DifFlow3D#1]
我照着指引下载了数据集后解压文件发现数据集的量极为庞大是，是正确情况吗？

**Comment by ERGOWHO** [comment]
I got 645.6 GiB on my side after extract

**Comment by ERGOWHO** [comment]
and "xxxx_processed_35m" is 115.5 GiB after preprocessed by their code
